[build]
  base = "evidence"
  # The line below sets the variables then runs your build scripts
  command = "export AWS_ACCESS_KEY_ID=$EVIDENCE_SOURCE__stockterrain__accessKeyId && export AWS_SECRET_ACCESS_KEY=$EVIDENCE_SOURCE__stockterrain__secretAccessKey && npm run sources && npm run build"
  publish = ".evidence/template/build"

[build.environment]
  AWS_REGION = "eu-central-1"
  AWS_DEFAULT_REGION = "eu-central-1"
  NODE_VERSION = "18"