
# Name the project
name: 'dbt_analytics'
version: '1.0.0'

# Set the profile
profile: 'stockterrain'

# The dbt specification
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


# Configuring models
models:
  dbt_analytics:

    
